version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./target/api-gen-barcode-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/casamento
      SPRING_R2DBC_USERNAME: admin
      SPRING_R2DBC_PASSWORD: 1234@
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: casamento
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d/:ro

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin

volumes:
  postgres_data:
  pgadmin_data: